version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: dockerfile/db.dockerfile 
    networks:
      - internal-network
    volumes:
      - ./db/sql:/etc/freeradius/host_sql

  backend:
    build:
      context: .
      dockerfile: dockerfile/backend.dockerfile
    networks:
      - internal-network
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: .
      dockerfile: dockerfile/frontend.dockerfile
    networks:
      - internal-network
    depends_on:
      - db
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src

networks:
  internal-network:
