version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: dockerfile/db.dockerfile 
    networks:
      - my-internal-network

  backend:
    build:
      context: .
      dockerfile: dockerfile/backend.dockerfile
    networks:
      - my-internal-network
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: .
      dockerfile: dockerfile/frontend.dockerfile
    networks:
      - my-internal-network
    depends_on:
      - db
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src

networks:
  my-internal-network:
    driver: bridge
