version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: dockerfile/db.dockerfile 
    networks:
      - internal-network
    volumes:
      - ./db/sql:/etc/freeradius/host_sql

  backend:
    build:
      context: .
      dockerfile: dockerfile/backend.dockerfile
    networks:
      - internal-network
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: dockerfile/frontend.dockerfile
    networks:
      - internal-network
    depends_on:
      - db
      - backend
    ports:
      - "5173:5173"

networks:
  internal-network:
